version: '3.7'

services:
  ts-node-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: ts-node-docker
    env_file:
      - .env
    expose:
      - '4000'
      - '9229'
    ports:
      - '4000:4000'
      - "9229:9229"
    command: npm run dev
  redis:
    image: redis:7.0.4-alpine
    container_name: redis
    restart: always
    environment:
      TZ: "America/Sao_Paulo"
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
  mongo:
    image: mongo:5.0
    restart: always
    volumes:
      - /data/db
    ports:
      - "27017:27017"
  mysql:
    image: woahbase/alpine-mysql:x86_64
    container_name: docker_mysql
    hostname: mysql
    environment:
      - PGID=100
      - PUID=1000
      - MYSQL_ROOT_PWD=password
      - MYSQL_USER=mysql
      - MYSQL_USER_PWD=password
      - MYSQL_USER_DB=bulario
    ports:
      - "3326:3306"
    volumes:
      - data:/var/lib/mysql
      - /etc/hosts:/etc/hosts:ro
      - /etc/localtime:/etc/localtime:ro
    command: ["sh", "-c", "tail -f /dev/null"]

  postgres:
    build: .docker/postgres
    container_name: bulario-db
    restart: always
    tty: true
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=bulario

volumes:
  data: