version: '3.7'

services:
  ts-node-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: ts-node-docker
    env_file:
      - .env
    expose:
      - '4000'
    ports:
      - '4000:4000'
    command: npm run dev
  redis:
    image: redis:7.0.4-alpine
    container_name: redis
    restart: always
    environment:
      TZ: "America/Sao_Paulo"
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
  mongo:
    image: mongo:5.0
    restart: always
    volumes:
      - /data/db
    ports:
      - "27017:27017"